import math
x=math.sqrt(64)
print(x)
print("////////////////////////////")
x=2
print(x**2)
print("------using ceil and floor---")
x=math.ceil(2.9)
y=math.floor(2.9)
print(x)
print(y)
print("////////////using pi////////////")
x=math.pi
print(x)
print("////////////using e/////////////////")
x=math.e
print(x)
print("////////////////////////////////")
x=math.radians(30)
y=math.degrees(360)
print(x)
print(y)
print("////////////////////////////////")
x=math.sin(math.pi/2)
y=math.cos(math.pi/2)
z=math.tan(math.pi/2)

print(x)
print(y)
print(z)
print("///////////using_math.log()/////////////////////")
x=math.log(10)
print(x)
print("///////////using_math.log10()/////////////////////")
x=math.log10(10)
print(x)
print("///////////using_math.exp()/////////////////////")
x=math.exp(10)
print(x)
print("---------------------------------")
x=math.e**10
print(x)