print("------Decimal_to_Binary-------")
a=25
print(bin(a))
print("------Binary_to_Decimal--------")
a=0b11001
print(a)
print("------Binary_to_Decimal--------")
a=0b1100111
print(oct(a))
print("------Decimal_to_octal--------")
a=25
print(oct(a))
print("------octal_to_Decimal--------")
a=0o31
print(a)
print("------Decimal_to_Hexdecimal--------")
a=10
print(hex(a))
a=11
print(hex(a))
a=12
print(hex(a))
a=13
print(hex(a))
a=14
print(hex(a))
a=15
print(hex(a))
a=141
print(hex(a))
print("------Hexdecimal_to_Decimal--------")
a=0x31
print(a)
print("---we can convert binary to decimal octal & hexdecimal--------")
a=0b11001
print(a)
print(oct(a))
print(hex(a))
print("---we can convert octal to decimal binary & hexdecimal--------")
a=215
print(a)
print(bin(a))
print(hex(a))
print("---we can convert hexdecimal to decimal binary & octal-------")
a=0x8d
print(a)
print(bin(a))
print(oct(a))